# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"
# Example 3:

# Input: s = "a", t = "aa"
# Output: "a"
# Example 4:

# Input: s = "ae", t = "aea"
# Output: "a"

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        Dict1 = {}
        Dict2 = {}
        
        for char in s:
            if char in Dict1:
                Dict1[char] += 1
            else:
                Dict1[char] = 1
        
        for char in t:
            if char in Dict2:
                Dict2[char] += 1
            else:
                Dict2[char] = 1
                
        for char in t:
            if char not in Dict1:
                return char
            else:
                if Dict1[char] != Dict2[char]:
                    return char
